services:
  api:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app_network

  tests:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "python wait_for_it.py && python test_api.py"
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
