services:
  api:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app_network

  tests:
    build: .
    command: python test_api.py
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
