name: CI/CD Breast Cancer API

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Test básico del endpoint
      run: |
        docker build -t breast-cancer-api .
        docker run -d -p 5000:5000 --name test-api breast-cancer-api
        # Bucle para esperar a que el servicio esté disponible
        echo "Esperando a que el servicio esté listo..."
        for i in $(seq 1 300); do
        if curl --output /dev/null --silent --head --fail http://localhost:5000/predict; then
        echo "✅ Servicio listo después de $i segundos."
        break
        fi
        sleep 1
        done

        # Si el bucle termina y el servicio no está listo, fallar
        if ! curl --output /dev/null --silent --head --fail http://localhost:5000/predict; then
        echo "❌ El servicio no se inició a tiempo."
        exit 1
        fi
        python test_api.py
        docker stop test-api

    - name: Login a Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push a Docker Hub
      run: |
        docker tag breast-cancer-api ${{ secrets.DOCKER_USERNAME }}/breast-cancer-api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/breast-cancer-api:latest
